import type { Metadata } from "next";
import "./globals.css";
import OverlayMenu from "@/components/html/organisms/menu/OverlayMenu";
import { Orbitron } from "next/font/google";

const orbit = Orbitron({
  subsets: ["latin"],
  variable: "--Orbitron",
  weight: ["400", "500", "600", "700", "800", "900"], // Choose the weights you need
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${orbit.variable} antialiased font-base`}>
        <div className="absolute overflow-visible z-30">
          <OverlayMenu></OverlayMenu>
        </div>
        <div className="relative z-0">{children}</div>
      </body>
    </html>
  );
}
